name: Build ncspot for Raspberry Pi

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          target: armv7-unknown-linux-gnueabihf

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y pkg-config libasound2-dev libssl-dev libdbus-1-dev

      - name: Build for Raspberry Pi
        run: cargo build --release --target armv7-unknown-linux-gnueabihf

      - name: Upload binary
        uses: actions/upload-artifact@v4
        with:
          name: ncspot-pi
          path: target/armv7-unknown-linux-gnueabihf/release/ncspot
